name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build
        run: |
          echo'Release created at  ${{ env.BUILDTIME }}
          Synchronize ${{ github.ref_name }} branch code updates, keeping only the latest version
          <br>  
          ### release version  
          `default(not specified in file name)`: compiled with GOAMD64=v3
          `cgo`: support lwip tun stack, compiled with GOAMD64=v1  
          `compatible`: compiled with GOAMD64=v1
          Check details between different architectural levels [here](https://github.com/golang/go/wiki/MinimumRequirements#amd64).' > Release.txt
        
      - name: Test
        run: cat Release.txt
        
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Release.txt
            LICENSE
